### ISSUE TITLE
Add more detail to the GitHub & Advanced Git Sections

### ISSUE THREAD

**Issue by johndbritton** [johndbritton/sinica#1]
Looking forward to those parts of class, but I'd really like more detail.

:hamburger: :star:

@muan Any suggestions

**Comment by grass0916** [comment]
:+1:

**Comment by muan** [comment]
I think CI is always a fun topic to talk about! :sparkles:

**Comment by PeterDaveHello** [comment]
What about git `bisect` and `blame`?

**Comment by clacha** [comment]
:+1:

**Comment by bookjan** [comment]
Nice~
